name: Hardhat Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Change to blockchain directory
        run: | 
          cd ./blockchain
          npm install

      - name: Compile contracts
        run: |
          cd ./blockchain
          npx hardhat compile

      - name: Run Hardhat tests
        run: |
          cd ./blockchain
          npx hardhat test