name: Hardhat Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockchain

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: | 
          npm install

      - name: Run Hardhat tests
        run: |
          npx hardhat test